<?php declare(strict_types=1);

namespace App\Enum;

enum SymbolEnum: string
{
    case BTCUSDT = 'BTCUSDT';
    case MEMEUSDT = 'MEMEUSDT';
    case NFPUSDT = 'NFPUSDT';
    case PEPEUSDT = 'PEPEUSDT';
    case ACEUSDT = 'ACEUSDT';
    case SSVUSDT = 'SSVUSDT';
    case TRXUSDT = 'TRXUSDT';
    case SOLUSDT = 'SOLUSDT';

//    case ALL_PAIRS = [
//        self::BTCUSDT, 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'USDCUSDT', 'ADAUSDT', 'AVAXUSDT', 'DOGEUSDT', 'DOTUSDT',
//        'TRXUSDT', 'MATICUSDT', 'LINKUSDT', 'WBTCUSDT', 'ICPUSDT', 'SHIBUSDT', 'LTCUSDT', 'BCHUSDT', 'UNIUSDT', 'ATOMUSDT',
//        'NEARUSDT', 'XLMUSDT', 'OPUSDT', 'FILUSDT', 'INJUSDT', 'APTUSDT', 'HBARUSDT', 'ETCUSDT', 'XMRUSDT', 'IMXUSDT',
//        'LDOUSDT', 'ARBUSDT', 'VETUSDT', 'TUSDUSDT', 'STXUSDT', 'TIAUSDT', 'FDUSDUSDT', 'RUNEUSDT', 'SEIUSDT', 'WBETHUSDT',
//        'GRTUSDT', 'RNDRUSDT', 'ALGOUSDT', 'MKRUSDT', 'ORDIUSDT', 'QNTUSDT', 'EGLDUSDT', 'AAVEUSDT', '1000SATSUSDT',
//        'MINAUSDT', 'FLOWUSDT', 'FTMUSDT', 'THETAUSDT', 'SANDUSDT', 'SNXUSDT', 'AXSUSDT', 'XTZUSDT', 'ASTRUSDT', 'FTTUSDT',
//        'SUIUSDT', 'PEOPLEUSDT', 'ENSUSDT', 'CYBERUSDT', 'POWRUSDT', 'PERPUSDT', 'BLURUSDT', 'MOVRUSDT', 'YGGUSDT', 'WLDUSDT',
//        'BONKUSDT', 'BAKEUSDT', 'CAKEUSDT', 'CHRUSDT', 'GMTUSDT', 'RDNTUSDT', 'TRXUSDT', 'GALAUSDT', 'SSVUSDT', 'MEMEUSDT',
//        'ACEUSDT', 'PEPEUSDT', 'NFPUSDT'
//    ];
}
